version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    networks:
      - project-network
    environment:
      - DB_HOST=backend
      - DB_PORT=8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - project-network
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Pranjal2607!@
      - DB_PORT=3306
      - DB_NAME=employees_db
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pranjal2607!@
      MYSQL_DATABASE: employees_db
    ports:
      - "3306:3306"
    networks:
      - project-network

networks:
  project-network:
    driver: bridge

